# Generated by Django 3.2.5 on 2021-08-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default=1, verbose_name='Опис'),
            preserve_default=False,
        ),
    ]
